/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Events */
    get: operations['events_v1_events_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations['health_v1_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/profile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Profile */
    get: operations['get_profile_v1_profile_get'];
    /** Save Profile */
    put: operations['save_profile_v1_profile_put'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/profile/evidence/{evidence_id}/verification': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Set Evidence Verification */
    put: operations['set_evidence_verification_v1_profile_evidence__evidence_id__verification_put'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/profile/resume': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Import Resume */
    post: operations['import_resume_v1_profile_resume_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/runs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Runs */
    get: operations['list_runs_v1_runs_get'];
    put?: never;
    /** Create Run */
    post: operations['create_run_v1_runs_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/runs/{run_id}/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Run Events */
    get: operations['list_run_events_v1_runs__run_id__events_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/runs/{run_id}/transitions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Transition Run */
    post: operations['transition_run_v1_runs__run_id__transitions_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ApplicationRun */
    ApplicationRun: {
      /**
       * Autosubmitauthorized
       * @default false
       */
      autoSubmitAuthorized: boolean;
      /**
       * Candidateprofileid
       * Format: uuid
       */
      candidateProfileId: string;
      /** Candidateprofileversion */
      candidateProfileVersion: number;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt?: string;
      /**
       * Id
       * Format: uuid
       */
      id?: string;
      /**
       * Jobid
       * Format: uuid
       */
      jobId: string;
      /**
       * Joburl
       * Format: uri
       */
      jobUrl: string;
      /** @default created */
      state: components['schemas']['WorkflowState'];
      /**
       * Updatedat
       * Format: date-time
       */
      updatedAt?: string;
    };
    /** Body_import_resume_v1_profile_resume_post */
    Body_import_resume_v1_profile_resume_post: {
      /** Expected Version */
      expected_version: number;
      /** File */
      file: string;
    };
    /** CandidateFact */
    CandidateFact: {
      /** Canonicalpath */
      canonicalPath: string;
      /** Evidenceids */
      evidenceIds?: string[];
      /**
       * Id
       * Format: uuid
       */
      id?: string;
      /** @default ordinary */
      sensitivity: components['schemas']['Sensitivity'];
      state: components['schemas']['FactState'];
      /** Value */
      value: string;
    };
    /** CandidateProfile */
    CandidateProfile: {
      /** Evidence */
      evidence?: components['schemas']['EvidenceItem'][];
      /** Facts */
      facts?: components['schemas']['CandidateFact'][];
      /**
       * Id
       * Format: uuid
       */
      id?: string;
      /** Sourcedocuments */
      sourceDocuments?: components['schemas']['SourceDocument'][];
      /**
       * Version
       * @default 1
       */
      version: number;
    };
    /** CandidateProfileInput */
    CandidateProfileInput: {
      /**
       * City
       * @default
       */
      city: string;
      /**
       * Country
       * @default United States
       */
      country: string;
      /**
       * Degree
       * @default
       */
      degree: string;
      /** Email */
      email: string;
      /**
       * Fieldofstudy
       * @default
       */
      fieldOfStudy: string;
      /** Firstname */
      firstName: string;
      /** Githuburl */
      githubUrl?: string | null;
      /** Graduationyear */
      graduationYear?: number | null;
      /** Lastname */
      lastName: string;
      /** Linkedinurl */
      linkedinUrl?: string | null;
      /**
       * Phone
       * @default
       */
      phone: string;
      /**
       * Postalcode
       * @default
       */
      postalCode: string;
      /**
       * Preferredname
       * @default
       */
      preferredName: string;
      /**
       * Region
       * @default
       */
      region: string;
      /** Requiressponsorship */
      requiresSponsorship?: boolean | null;
      /**
       * School
       * @default
       */
      school: string;
      /**
       * Workauthorization
       * @default unspecified
       * @enum {string}
       */
      workAuthorization: 'unspecified' | 'authorized' | 'requires_sponsorship' | 'not_authorized';
    };
    /** CandidateProfileSnapshot */
    CandidateProfileSnapshot: {
      profile: components['schemas']['CandidateProfile'];
      /**
       * Updatedat
       * Format: date-time
       */
      updatedAt?: string;
    };
    /** CreateRunRequest */
    CreateRunRequest: {
      /**
       * Autosubmitauthorized
       * @default false
       */
      autoSubmitAuthorized: boolean;
      /**
       * Candidateprofileid
       * Format: uuid
       */
      candidateProfileId: string;
      /** Candidateprofileversion */
      candidateProfileVersion: number;
      /**
       * Jobid
       * Format: uuid
       */
      jobId: string;
      /**
       * Joburl
       * Format: uri
       */
      jobUrl: string;
      /**
       * Startimmediately
       * @default true
       */
      startImmediately: boolean;
    };
    /**
     * DocumentStatus
     * @enum {string}
     */
    DocumentStatus: 'parsed' | 'needs_ocr' | 'failed';
    /** EvidenceItem */
    EvidenceItem: {
      /** Confidence */
      confidence: number;
      /**
       * Extractionmethod
       * @enum {string}
       */
      extractionMethod: 'deterministic' | 'model' | 'user';
      /**
       * Id
       * Format: uuid
       */
      id?: string;
      /** Sourcedocumentid */
      sourceDocumentId?: string | null;
      sourceSpan?: components['schemas']['SourceSpan'] | null;
      /** Statement */
      statement: string;
      /**
       * Verified
       * @default false
       */
      verified: boolean;
    };
    /**
     * FactState
     * @enum {string}
     */
    FactState: 'extracted' | 'needs_review' | 'verified' | 'superseded' | 'deleted';
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** HealthStatus */
    HealthStatus: {
      /** Browserworkerconnected */
      browserWorkerConnected: boolean;
      /** Databaseready */
      databaseReady: boolean;
      /**
       * Service
       * @default careerflow-agent
       */
      service: string;
      /**
       * Status
       * @enum {string}
       */
      status: 'starting' | 'ready' | 'degraded' | 'stopped';
      /** Telemetryready */
      telemetryReady: boolean;
      /** Version */
      version: string;
    };
    /** ResumeImportResult */
    ResumeImportResult: {
      document: components['schemas']['SourceDocument'];
      snapshot: components['schemas']['CandidateProfileSnapshot'];
    };
    /** SaveCandidateProfileRequest */
    SaveCandidateProfileRequest: {
      /** Expectedversion */
      expectedVersion?: number | null;
      profile: components['schemas']['CandidateProfileInput'];
    };
    /**
     * Sensitivity
     * @enum {string}
     */
    Sensitivity: 'ordinary' | 'sensitive' | 'legal' | 'demographic';
    /** SetEvidenceVerificationRequest */
    SetEvidenceVerificationRequest: {
      /** Expectedversion */
      expectedVersion: number;
      /** Verified */
      verified: boolean;
    };
    /** SourceDocument */
    SourceDocument: {
      /** Encryptedartifactref */
      encryptedArtifactRef: string;
      /**
       * Extractedevidencecount
       * @default 0
       */
      extractedEvidenceCount: number;
      /** Filename */
      filename: string;
      /**
       * Id
       * Format: uuid
       */
      id?: string;
      /**
       * Importedat
       * Format: date-time
       */
      importedAt?: string;
      /**
       * Mediatype
       * @enum {string}
       */
      mediaType:
        | 'application/pdf'
        | 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
      /** Parseerrorcode */
      parseErrorCode?: string | null;
      /** Sha256 */
      sha256: string;
      /** @default parsed */
      status: components['schemas']['DocumentStatus'];
    };
    /** SourceSpan */
    SourceSpan: {
      /** End */
      end: number;
      /** Page */
      page?: number | null;
      /** Section */
      section?: string | null;
      /** Start */
      start: number;
    };
    /** TransitionRequest */
    TransitionRequest: {
      /** Idempotencykey */
      idempotencyKey: string;
      /** Reasoncode */
      reasonCode: string;
      toState: components['schemas']['WorkflowState'];
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** WorkflowEvent */
    WorkflowEvent: {
      /** Eventtype */
      eventType: string;
      fromState?: components['schemas']['WorkflowState'] | null;
      /**
       * Id
       * Format: uuid
       */
      id?: string;
      /**
       * Occurredat
       * Format: date-time
       */
      occurredAt?: string;
      /** Reasoncode */
      reasonCode: string;
      /**
       * Runid
       * Format: uuid
       */
      runId: string;
      /** Safedetails */
      safeDetails?: {
        [key: string]: string | number | boolean | null;
      };
      /** Sequence */
      sequence: number;
      toState: components['schemas']['WorkflowState'];
    };
    /**
     * WorkflowState
     * @enum {string}
     */
    WorkflowState:
      | 'created'
      | 'ingesting_job'
      | 'preparing_materials'
      | 'opening_application'
      | 'authenticating'
      | 'registering'
      | 'verifying_email'
      | 'filling'
      | 'awaiting_human'
      | 'validating'
      | 'ready_to_submit'
      | 'submitting'
      | 'submitted'
      | 'failed'
      | 'cancelled'
      | 'outcome_uncertain';
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  events_v1_events_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  health_v1_health_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthStatus'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_profile_v1_profile_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CandidateProfileSnapshot'] | null;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  save_profile_v1_profile_put: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SaveCandidateProfileRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CandidateProfileSnapshot'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  set_evidence_verification_v1_profile_evidence__evidence_id__verification_put: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        evidence_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SetEvidenceVerificationRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CandidateProfileSnapshot'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  import_resume_v1_profile_resume_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_import_resume_v1_profile_resume_post'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ResumeImportResult'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_runs_v1_runs_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApplicationRun'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_run_v1_runs_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateRunRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApplicationRun'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_run_events_v1_runs__run_id__events_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkflowEvent'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  transition_run_v1_runs__run_id__transitions_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TransitionRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkflowEvent'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
