/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/application-statistics': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Application Statistics */
    get: operations['application_statistics_v1_application_statistics_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/demo/synthetic-run': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start Synthetic Run */
    post: operations['start_synthetic_run_v1_demo_synthetic_run_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Events */
    get: operations['events_v1_events_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations['health_v1_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/jobs/ingest': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Ingest Job */
    post: operations['ingest_job_v1_jobs_ingest_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/jobs/{job_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Job */
    get: operations['get_job_v1_jobs__job_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/materials/prepare': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Prepare Materials */
    post: operations['prepare_materials_v1_materials_prepare_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/profile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Profile */
    get: operations['get_profile_v1_profile_get'];
    /** Save Profile */
    put: operations['save_profile_v1_profile_put'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/profile/evidence/{evidence_id}/verification': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Set Evidence Verification */
    put: operations['set_evidence_verification_v1_profile_evidence__evidence_id__verification_put'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/profile/resume': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Import Resume */
    post: operations['import_resume_v1_profile_resume_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/profile/resume/preview': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Preview Resume */
    post: operations['preview_resume_v1_profile_resume_preview_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/runs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Runs */
    get: operations['list_runs_v1_runs_get'];
    put?: never;
    /** Create Run */
    post: operations['create_run_v1_runs_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/runs/{run_id}/checkpoint': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Latest Checkpoint */
    get: operations['get_latest_checkpoint_v1_runs__run_id__checkpoint_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/runs/{run_id}/control': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Control Run */
    post: operations['control_run_v1_runs__run_id__control_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/runs/{run_id}/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Run Events */
    get: operations['list_run_events_v1_runs__run_id__events_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/runs/{run_id}/field-explanations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Field Explanations */
    get: operations['list_field_explanations_v1_runs__run_id__field_explanations_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/runs/{run_id}/outcome': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Record Application Outcome */
    put: operations['record_application_outcome_v1_runs__run_id__outcome_put'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/runs/{run_id}/outcomes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Application Outcomes */
    get: operations['list_application_outcomes_v1_runs__run_id__outcomes_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/runs/{run_id}/transitions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Transition Run */
    post: operations['transition_run_v1_runs__run_id__transitions_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ApplicationMaterialPlan */
    ApplicationMaterialPlan: {
      /**
       * Candidateprofileid
       * Format: uuid
       */
      candidateProfileId: string;
      /** Candidateprofileversion */
      candidateProfileVersion: number;
      /** Coverageratio */
      coverageRatio: number;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt?: string;
      /**
       * Generatorversion
       * @default deterministic-v1
       * @constant
       */
      generatorVersion: 'deterministic-v1';
      /**
       * Jobid
       * Format: uuid
       */
      jobId: string;
      /** Jobversion */
      jobVersion: number;
      /** Mappings */
      mappings?: components['schemas']['RequirementEvidenceMapping'][];
      /**
       * Modelused
       * @default false
       * @constant
       */
      modelUsed: false;
      /** Partialcount */
      partialCount: number;
      resumeDraft: components['schemas']['GroundedResumeDraft'];
      status: components['schemas']['MaterialPlanStatus'];
      /** Supportedcount */
      supportedCount: number;
      /** Unsupportedcount */
      unsupportedCount: number;
    };
    /** ApplicationOutcome */
    ApplicationOutcome: {
      /** Confirmation */
      confirmation?: components['schemas']['ConfirmationEvidence'][];
      /**
       * Id
       * Format: uuid
       */
      id?: string;
      outcome: components['schemas']['OutcomeType'];
      reasonCode: components['schemas']['OutcomeReasonCode'];
      /**
       * Recordedat
       * Format: date-time
       */
      recordedAt?: string;
      /**
       * Recordedby
       * @default user
       * @constant
       */
      recordedBy: 'user';
      /** Revision */
      revision: number;
      /**
       * Runid
       * Format: uuid
       */
      runId: string;
      /** Supersedesid */
      supersedesId?: string | null;
    };
    /** ApplicationRun */
    ApplicationRun: {
      /**
       * Autosubmitauthorized
       * @default false
       */
      autoSubmitAuthorized: boolean;
      /**
       * Candidateprofileid
       * Format: uuid
       */
      candidateProfileId: string;
      /** Candidateprofileversion */
      candidateProfileVersion: number;
      /** Company */
      company?: string | null;
      /**
       * Createdat
       * Format: date-time
       */
      createdAt?: string;
      /**
       * Id
       * Format: uuid
       */
      id?: string;
      /**
       * Jobid
       * Format: uuid
       */
      jobId: string;
      /** Jobtitle */
      jobTitle?: string | null;
      /**
       * Joburl
       * Format: uri
       */
      jobUrl: string;
      latestOutcome?: components['schemas']['ApplicationOutcome'] | null;
      platform?: components['schemas']['Platform'] | null;
      /** @default created */
      state: components['schemas']['WorkflowState'];
      /**
       * Updatedat
       * Format: date-time
       */
      updatedAt?: string;
    };
    /** ApplicationStatistics */
    ApplicationStatistics: {
      /** Abandoned */
      abandoned: number;
      /** Cancelled */
      cancelled: number;
      /** Failed */
      failed: number;
      /**
       * Generatedat
       * Format: date-time
       */
      generatedAt?: string;
      /** Outcomeuncertain */
      outcomeUncertain: number;
      /** Pendingruns */
      pendingRuns: number;
      /** Resolutionrate */
      resolutionRate: number;
      /** Resolvedruns */
      resolvedRuns: number;
      /** Submitted */
      submitted: number;
      /** Submittedrate */
      submittedRate: number;
      /** Totalruns */
      totalRuns: number;
    };
    /** Body_import_resume_v1_profile_resume_post */
    Body_import_resume_v1_profile_resume_post: {
      /** Expected Version */
      expected_version: number;
      /** File */
      file: string;
    };
    /** Body_preview_resume_v1_profile_resume_preview_post */
    Body_preview_resume_v1_profile_resume_preview_post: {
      /** File */
      file: string;
    };
    /** CandidateFact */
    CandidateFact: {
      /** Canonicalpath */
      canonicalPath: string;
      /** Evidenceids */
      evidenceIds?: string[];
      /**
       * Id
       * Format: uuid
       */
      id?: string;
      /** @default ordinary */
      sensitivity: components['schemas']['Sensitivity'];
      state: components['schemas']['FactState'];
      /** Value */
      value: string;
    };
    /** CandidateProfile */
    CandidateProfile: {
      /** Evidence */
      evidence?: components['schemas']['EvidenceItem'][];
      /** Facts */
      facts?: components['schemas']['CandidateFact'][];
      /**
       * Id
       * Format: uuid
       */
      id?: string;
      /** Sourcedocuments */
      sourceDocuments?: components['schemas']['SourceDocument'][];
      /**
       * Version
       * @default 1
       */
      version: number;
    };
    /** CandidateProfileInput */
    CandidateProfileInput: {
      /**
       * City
       * @default
       */
      city: string;
      /**
       * Country
       * @default United States
       */
      country: string;
      /**
       * Degree
       * @default
       */
      degree: string;
      /** Email */
      email: string;
      /**
       * Fieldofstudy
       * @default
       */
      fieldOfStudy: string;
      /** Firstname */
      firstName: string;
      /** Githuburl */
      githubUrl?: string | null;
      /** Graduationyear */
      graduationYear?: number | null;
      /** Lastname */
      lastName: string;
      /** Linkedinurl */
      linkedinUrl?: string | null;
      /**
       * Phone
       * @default
       */
      phone: string;
      /**
       * Postalcode
       * @default
       */
      postalCode: string;
      /**
       * Preferredname
       * @default
       */
      preferredName: string;
      /**
       * Region
       * @default
       */
      region: string;
      /** Requiressponsorship */
      requiresSponsorship?: boolean | null;
      /**
       * School
       * @default
       */
      school: string;
      /**
       * Workauthorization
       * @default unspecified
       * @enum {string}
       */
      workAuthorization: 'unspecified' | 'authorized' | 'requires_sponsorship' | 'not_authorized';
    };
    /** CandidateProfileSnapshot */
    CandidateProfileSnapshot: {
      profile: components['schemas']['CandidateProfile'];
      /**
       * Updatedat
       * Format: date-time
       */
      updatedAt?: string;
    };
    /** Checkpoint */
    Checkpoint: {
      /**
       * Createdat
       * Format: date-time
       */
      createdAt?: string;
      /**
       * Id
       * Format: uuid
       */
      id?: string;
      /** Idempotencykey */
      idempotencyKey: string;
      /**
       * Runid
       * Format: uuid
       */
      runId: string;
      /** Sequence */
      sequence: number;
      state: components['schemas']['WorkflowState'];
      /** Stepid */
      stepId: string;
    };
    /** ConfirmationEvidence */
    ConfirmationEvidence: {
      /** Artifactref */
      artifactRef?: string | null;
      /**
       * Capturedat
       * Format: date-time
       */
      capturedAt?: string;
      /** Fingerprint */
      fingerprint: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: 'confirmation_page' | 'application_id' | 'confirmation_email' | 'user_correction';
    };
    /** CreateRunRequest */
    CreateRunRequest: {
      /**
       * Autosubmitauthorized
       * @default false
       */
      autoSubmitAuthorized: boolean;
      /**
       * Candidateprofileid
       * Format: uuid
       */
      candidateProfileId: string;
      /** Candidateprofileversion */
      candidateProfileVersion: number;
      /**
       * Jobid
       * Format: uuid
       */
      jobId: string;
      /**
       * Joburl
       * Format: uri
       */
      jobUrl: string;
      /**
       * Startimmediately
       * @default true
       */
      startImmediately: boolean;
    };
    /**
     * DocumentStatus
     * @enum {string}
     */
    DocumentStatus: 'parsed' | 'needs_ocr' | 'failed';
    /** EvidenceItem */
    EvidenceItem: {
      /** Confidence */
      confidence: number;
      /**
       * Extractionmethod
       * @enum {string}
       */
      extractionMethod: 'deterministic' | 'model' | 'user';
      /**
       * Id
       * Format: uuid
       */
      id?: string;
      /** Sourcedocumentid */
      sourceDocumentId?: string | null;
      sourceSpan?: components['schemas']['SourceSpan'] | null;
      /** Statement */
      statement: string;
      /**
       * Verified
       * @default false
       */
      verified: boolean;
    };
    /** EvidenceMatch */
    EvidenceMatch: {
      /**
       * Evidenceid
       * Format: uuid
       */
      evidenceId: string;
      /** Matchedterms */
      matchedTerms?: string[];
      /** Score */
      score: number;
      /** Sourcedocumentid */
      sourceDocumentId?: string | null;
      sourceSpan?: components['schemas']['SourceSpan'] | null;
      /** Statement */
      statement: string;
    };
    /**
     * FactState
     * @enum {string}
     */
    FactState: 'extracted' | 'needs_review' | 'verified' | 'superseded' | 'deleted';
    /** FieldExplanation */
    FieldExplanation: {
      /** Canonicalpath */
      canonicalPath?: string | null;
      /** Confidence */
      confidence: number;
      /** Controlid */
      controlId: string;
      decision: components['schemas']['MappingDecision'];
      /** Filled */
      filled: boolean;
      /**
       * Id
       * Format: uuid
       */
      id?: string;
      /** Pagestatehash */
      pageStateHash: string;
      /** Rationale */
      rationale: string;
      /**
       * Recordedat
       * Format: date-time
       */
      recordedAt?: string;
      /**
       * Runid
       * Format: uuid
       */
      runId: string;
      sensitivity: components['schemas']['Sensitivity'];
      /**
       * Source
       * @enum {string}
       */
      source: 'adapter' | 'deterministic' | 'model' | 'user';
      /** Stepid */
      stepId: string;
    };
    /** GroundedResumeDraft */
    GroundedResumeDraft: {
      /** Entries */
      entries?: components['schemas']['GroundedResumeEntry'][];
      /** Title */
      title: string;
    };
    /** GroundedResumeEntry */
    GroundedResumeEntry: {
      /**
       * Evidenceid
       * Format: uuid
       */
      evidenceId: string;
      /** Sourcedocumentid */
      sourceDocumentId?: string | null;
      sourceSpan?: components['schemas']['SourceSpan'] | null;
      /** Statement */
      statement: string;
      /** Supportsrequirementids */
      supportsRequirementIds?: string[];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** HealthStatus */
    HealthStatus: {
      /** Browserworkerconnected */
      browserWorkerConnected: boolean;
      /** Databaseready */
      databaseReady: boolean;
      /**
       * Service
       * @default careerflow-agent
       */
      service: string;
      /**
       * Status
       * @enum {string}
       */
      status: 'starting' | 'ready' | 'degraded' | 'stopped';
      /** Telemetryready */
      telemetryReady: boolean;
      /** Version */
      version: string;
    };
    /** IngestJobRequest */
    IngestJobRequest: {
      /**
       * Url
       * Format: uri
       */
      url: string;
    };
    /**
     * JobIngestionStatus
     * @enum {string}
     */
    JobIngestionStatus: 'complete' | 'needs_review';
    /** JobPosting */
    JobPosting: {
      /**
       * Canonicalurl
       * Format: uri
       */
      canonicalUrl: string;
      /** Company */
      company: string;
      /** Description */
      description: string;
      /** Descriptionhash */
      descriptionHash: string;
      /**
       * Id
       * Format: uuid
       */
      id?: string;
      /**
       * Location
       * @default
       */
      location: string;
      platform: components['schemas']['PlatformDetection'];
      /** Requirements */
      requirements?: components['schemas']['JobRequirement'][];
      /**
       * Resolvedurl
       * Format: uri
       */
      resolvedUrl: string;
      /**
       * Retrievedat
       * Format: date-time
       */
      retrievedAt?: string;
      /**
       * Sourceurl
       * Format: uri
       */
      sourceUrl: string;
      status: components['schemas']['JobIngestionStatus'];
      /** Supersedesid */
      supersedesId?: string | null;
      /** Title */
      title: string;
      /**
       * Version
       * @default 1
       */
      version: number;
      /** Warnings */
      warnings?: string[];
    };
    /** JobRequirement */
    JobRequirement: {
      /**
       * Id
       * Format: uuid
       */
      id?: string;
      /** Required */
      required: boolean;
      sourceSpan: components['schemas']['SourceSpan'];
      /** Text */
      text: string;
    };
    /**
     * MappingDecision
     * @enum {string}
     */
    MappingDecision: 'auto_fill' | 'review' | 'human_required' | 'unsupported';
    /**
     * MaterialPlanStatus
     * @enum {string}
     */
    MaterialPlanStatus: 'needs_review' | 'needs_evidence';
    /**
     * OutcomeReasonCode
     * @enum {string}
     */
    OutcomeReasonCode:
      | 'user_confirmed_submitted'
      | 'ingestion_failed'
      | 'evidence_missing'
      | 'authentication_failed'
      | 'registration_failed'
      | 'verification_failed'
      | 'mapping_failed'
      | 'validation_failed'
      | 'submission_failed'
      | 'platform_changed'
      | 'policy_blocked'
      | 'user_cancelled'
      | 'user_abandoned'
      | 'confirmation_missing';
    /**
     * OutcomeType
     * @enum {string}
     */
    OutcomeType: 'submitted' | 'failed' | 'cancelled' | 'abandoned' | 'outcome_uncertain';
    /**
     * Platform
     * @enum {string}
     */
    Platform: 'synthetic' | 'workday' | 'greenhouse' | 'lever' | 'unknown';
    /** PlatformDetection */
    PlatformDetection: {
      /** Confidence */
      confidence: number;
      platform: components['schemas']['Platform'];
      /** Signals */
      signals?: string[];
    };
    /** PrepareMaterialsRequest */
    PrepareMaterialsRequest: {
      /**
       * Candidateprofileid
       * Format: uuid
       */
      candidateProfileId: string;
      /** Candidateprofileversion */
      candidateProfileVersion: number;
      /**
       * Jobid
       * Format: uuid
       */
      jobId: string;
    };
    /** RecordApplicationOutcomeRequest */
    RecordApplicationOutcomeRequest: {
      /**
       * Confirmedbyuser
       * @constant
       */
      confirmedByUser: true;
      outcome: components['schemas']['OutcomeType'];
      reasonCode: components['schemas']['OutcomeReasonCode'];
    };
    /** RequirementEvidenceMapping */
    RequirementEvidenceMapping: {
      /** Confidence */
      confidence: number;
      /** Explanation */
      explanation: string;
      /** Matches */
      matches?: components['schemas']['EvidenceMatch'][];
      /** Required */
      required: boolean;
      /**
       * Requirementid
       * Format: uuid
       */
      requirementId: string;
      /** Requirementtext */
      requirementText: string;
      support: components['schemas']['RequirementSupport'];
    };
    /**
     * RequirementSupport
     * @enum {string}
     */
    RequirementSupport: 'supported' | 'partial' | 'unsupported';
    /** ResumeFieldSuggestion */
    ResumeFieldSuggestion: {
      canonicalPath: components['schemas']['ResumeSuggestionPath'];
      /** Confidence */
      confidence: number;
      sourceSpan: components['schemas']['SourceSpan'];
      /** Value */
      value: string;
    };
    /** ResumeImportResult */
    ResumeImportResult: {
      document: components['schemas']['SourceDocument'];
      snapshot: components['schemas']['CandidateProfileSnapshot'];
    };
    /** ResumePreviewResult */
    ResumePreviewResult: {
      /** Extractedevidencecount */
      extractedEvidenceCount: number;
      /** Parseerrorcode */
      parseErrorCode?: string | null;
      status: components['schemas']['DocumentStatus'];
      /** Suggestions */
      suggestions?: components['schemas']['ResumeFieldSuggestion'][];
    };
    /** @enum {string} */
    ResumeSuggestionPath:
      | 'identity.first_name'
      | 'identity.last_name'
      | 'contact.email'
      | 'contact.phone'
      | 'links.linkedin'
      | 'links.github'
      | 'education.0.school'
      | 'education.0.degree'
      | 'education.0.field_of_study'
      | 'education.0.graduation_year';
    /** RunControlRequest */
    RunControlRequest: {
      /**
       * Command
       * @enum {string}
       */
      command: 'pause' | 'resume' | 'cancel';
      /** Idempotencykey */
      idempotencyKey: string;
    };
    /** SaveCandidateProfileRequest */
    SaveCandidateProfileRequest: {
      /** Expectedversion */
      expectedVersion?: number | null;
      profile: components['schemas']['CandidateProfileInput'];
    };
    /**
     * Sensitivity
     * @enum {string}
     */
    Sensitivity: 'ordinary' | 'sensitive' | 'legal' | 'demographic';
    /** SetEvidenceVerificationRequest */
    SetEvidenceVerificationRequest: {
      /** Expectedversion */
      expectedVersion: number;
      /** Verified */
      verified: boolean;
    };
    /** SourceDocument */
    SourceDocument: {
      /** Encryptedartifactref */
      encryptedArtifactRef: string;
      /**
       * Extractedevidencecount
       * @default 0
       */
      extractedEvidenceCount: number;
      /** Filename */
      filename: string;
      /**
       * Id
       * Format: uuid
       */
      id?: string;
      /**
       * Importedat
       * Format: date-time
       */
      importedAt?: string;
      /**
       * Mediatype
       * @enum {string}
       */
      mediaType:
        | 'application/pdf'
        | 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
      /** Parseerrorcode */
      parseErrorCode?: string | null;
      /** Sha256 */
      sha256: string;
      /** @default parsed */
      status: components['schemas']['DocumentStatus'];
    };
    /** SourceSpan */
    SourceSpan: {
      /** End */
      end: number;
      /** Page */
      page?: number | null;
      /** Section */
      section?: string | null;
      /** Start */
      start: number;
    };
    /** StartSyntheticDemoRequest */
    StartSyntheticDemoRequest: {
      /**
       * Candidateprofileid
       * Format: uuid
       */
      candidateProfileId: string;
      /** Candidateprofileversion */
      candidateProfileVersion: number;
    };
    /** TransitionRequest */
    TransitionRequest: {
      /** Idempotencykey */
      idempotencyKey: string;
      /** Reasoncode */
      reasonCode: string;
      toState: components['schemas']['WorkflowState'];
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** WorkflowEvent */
    WorkflowEvent: {
      /** Eventtype */
      eventType: string;
      fromState?: components['schemas']['WorkflowState'] | null;
      /**
       * Id
       * Format: uuid
       */
      id?: string;
      /**
       * Occurredat
       * Format: date-time
       */
      occurredAt?: string;
      /** Reasoncode */
      reasonCode: string;
      /**
       * Runid
       * Format: uuid
       */
      runId: string;
      /** Safedetails */
      safeDetails?: {
        [key: string]: string | number | boolean | null;
      };
      /** Sequence */
      sequence: number;
      toState: components['schemas']['WorkflowState'];
    };
    /**
     * WorkflowState
     * @enum {string}
     */
    WorkflowState:
      | 'created'
      | 'ingesting_job'
      | 'preparing_materials'
      | 'opening_application'
      | 'authenticating'
      | 'registering'
      | 'verifying_email'
      | 'filling'
      | 'paused'
      | 'awaiting_human'
      | 'validating'
      | 'ready_to_submit'
      | 'submitting'
      | 'submitted'
      | 'failed'
      | 'cancelled'
      | 'outcome_uncertain';
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  application_statistics_v1_application_statistics_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApplicationStatistics'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  start_synthetic_run_v1_demo_synthetic_run_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['StartSyntheticDemoRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApplicationRun'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  events_v1_events_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  health_v1_health_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthStatus'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  ingest_job_v1_jobs_ingest_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['IngestJobRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JobPosting'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_job_v1_jobs__job_id__get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JobPosting'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  prepare_materials_v1_materials_prepare_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PrepareMaterialsRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApplicationMaterialPlan'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_profile_v1_profile_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CandidateProfileSnapshot'] | null;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  save_profile_v1_profile_put: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SaveCandidateProfileRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CandidateProfileSnapshot'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  set_evidence_verification_v1_profile_evidence__evidence_id__verification_put: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        evidence_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SetEvidenceVerificationRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CandidateProfileSnapshot'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  import_resume_v1_profile_resume_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_import_resume_v1_profile_resume_post'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ResumeImportResult'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  preview_resume_v1_profile_resume_preview_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_preview_resume_v1_profile_resume_preview_post'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ResumePreviewResult'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_runs_v1_runs_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApplicationRun'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_run_v1_runs_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateRunRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApplicationRun'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_latest_checkpoint_v1_runs__run_id__checkpoint_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Checkpoint'] | null;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  control_run_v1_runs__run_id__control_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RunControlRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApplicationRun'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_run_events_v1_runs__run_id__events_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkflowEvent'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_field_explanations_v1_runs__run_id__field_explanations_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FieldExplanation'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  record_application_outcome_v1_runs__run_id__outcome_put: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RecordApplicationOutcomeRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApplicationOutcome'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_application_outcomes_v1_runs__run_id__outcomes_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApplicationOutcome'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  transition_run_v1_runs__run_id__transitions_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TransitionRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WorkflowEvent'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
